apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: workshop
  labels:
    app: fluentd
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/*.log
      pos_file /var/log/fluentd.pos
      tag kubernetes.*
      format json
    </source>

    <match kubernetes.**>
      @type stdout
    </match>
