apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-pvc
  namespace: workshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: datastore
